### PR TITLE
Hotspot Editor v2

### PR DESCRIPTION
**Pull request by rroux-gpsw**
Editor plugin !
Please checkout editor-2 branches from sources and samples :)

### CODE REVIEW

**Comment by sw-team-release-gpsw** [comment]
[CLA assistant check](https://cla.gopro.com/sign) <br/>All committers have signed the CLA.

**Comment by bbaudel** [comment]
Observation for future update:
Click on center of the scale update X, Y and Z values. Z value is not needed depending of the geometry used. For flat geometry it's not needed.
So, if a flat geometry is detected, the Z axis must be ignored.

**Comment by bbaudel** [comment]
Warning : Still a loading issue of the plugin which is not reproductible.

**Review by bbaudel — APPROVED** [review]
LGTM for a v2

**Comment by aberthet-gpsw** [comment]
A very good improvement, yay ! Few suggestions:

* the scale is too sensitive
* when adding a hotspot, it should be facing the camera, as when adding a hotspot on another face than front, the hotspot is almost or entirely invisible
* when changing a value in text field with keyboard arrows, the value change as well as the camera: camera should be locked
* you forgot to update the UI of loading

Otherwise I don't see anything wrong, good work ! Hope to see one day a full editor ;)

**Pull request merged**
