### PR TITLE
Rroux dev

### PR DESCRIPTION
**Pull request by rroux-gpsw**
Add a Debug plugin that expose camera, view and story

### CODE REVIEW

**Comment by sw-team-release-gpsw** [comment]
[CLA assistant check](https://cla.gopro.com/sign) <br/>All committers have signed the CLA.

**Review by bbaudel — CHANGES_REQUESTED** [review]
Nice.
Need to remove the hotspots from the first scene while the flat view doesn't support them.

**Comment by ygilquin-gpsw** [comment]
Tested and approved.

**Review by ygilquin-gpsw — APPROVED** [review]
Tested and approved.

**Review by bbaudel — APPROVED** [review]

**Pull request merged**
