### PR TITLE
Alps 593 drag to pointer controller

### PR DESCRIPTION
**Pull request by rroux-gpsw**
Add a controller pannel + options to the Toolbox

### CODE REVIEW

**Comment by sw-team-release-gpsw** [comment]
[CLA assistant check](https://cla.gopro.com/sign) <br/>All committers have signed the CLA.

**Review by bbaudel — COMMENTED** [review]
LGTM
Option for revert axis also on drag ?

**Comment by rroux-gpsw** [comment]
It implies sources modifications to revert axis for drag

**Review by bbaudel — APPROVED** [review]
LGTM

**Pull request merged**
