### PR TITLE
Add the GamepadMonitor plugin

### PR DESCRIPTION
**Pull request by aberthet-gpsw**
Very simple plugin, displaying information on the current state of a gamepad. It is based on dat.gui

### CODE REVIEW

**Comment by sw-team-release-gpsw** [comment]
[CLA assistant check](https://cla.gopro.com/sign) <br/>All committers have signed the CLA.

**Review by bbaudel — CHANGES_REQUESTED** [review]
**Windows test**
* Chrome 👍 
* Firefox : broke the axis and button updates
* Edge 👍 
* IE11 : support of IE11 must be removed from the plugin with device option due to the non support of the Gamepad web api.

**Comment by aberthet-gpsw** [comment]
So I couldn't find a solution to make it work in Firefox. I suggest to let the plugin available only in Chrome, if it's okay with you. It is only a debug plugin, so I think if developers want to use it, they will launch Chrome for this part.

**Comment by bbaudel** [comment]
Also working on Edge and probably on Opera too.
So removing Safari and Firefox will be better.

**Comment by aberthet-gpsw** [comment]
Yes indeed, after a few tests it seems like it. Updated in last commit.

**Review by bbaudel — APPROVED** [review]

**Comment by bbaudel** [comment]
LGTM

**Pull request merged**
